model_config:
    seed:
    verbose: True
    device: cpu # cpu or cuda (cuda:1)
    fp16: False # whether to use half precision
    model_path: # the path to pretrained model

learner_config:
    seed:
    verbose: True
    progress_bar: True
    n_epochs: 1
    optimizer_config:
        optimizer: adam
        lr: 0.001
        l2: 0.0
        grad_clip: 1.0
        sgd_config:
            momentum: 0.9
        adam_config:
            betas: !!python/tuple [0.9, 0.999]
    lr_scheduler_config:
        lr_scheduler:
    task_scheduler: sequential

evaluation_config:

logging_config:
    counter_unit: epoch # [epoch, batch]
    evaluation_freq: 1.0
    checkpointing_freq: 2

writer_config:
    writer: tensorboard # [json, tensorboard]
    verbose: True