model_config:
    seed:
    verbose: True
    device: cpu # cpu or cuda (cuda:1)
    fp16: False # whether to use half precision
    model_path: # the path to pretrained model

learner_config:
    seed:
    verbose: True
    progress_bar: True
    n_epochs: 1
    train_split: train
    valid_split: valid
    test_split: test
    optimizer_config:
        optimizer: adam # [sgd, adam]
        lr: 0.001
        l2: 0.0
        grad_clip: 1.0
        sgd_config:
            momentum: 0.9
        adam_config:
            betas: !!python/tuple [0.9, 0.999]
    lr_scheduler_config:
        lr_scheduler: # [linear, exponential, reduce_on_plateau]
        warmup_steps: 0.0
        warmup_unit: epoch # [epoch, batch]
        min_lr: 0.0
        linear_config:
            min_lr: 0.0
        exponential_config:
            gamma: 0.9
        plateau_config:
            factor: 0.5
            patience: 10
            threshold: 0.0001
    task_scheduler: sequential

logging_config:
    counter_unit: batch # [epoch, batch]
    evaluation_freq: 10
    writer_config:
        writer: tensorboard # [json, tensorboard]
        verbose: True
    checkpointint: True
    checkpointer_config:
        checkpoint_path:
        checkpoint_freq: 2
        checkpoint_metric: task1/da1/valid/f1
        checkpoint_metric_mode: max # [min, max]
        checkpoint_runway: 0

