model_config:
    seed:
    verbose: True
    device: cpu # cpu or cuda (cuda:1)
    fp16: False # whether to use half precision
    model_path: # the path to pretrained model

learner_config:
    seed:
    verbose: True
    n_epochs: 1
    optimizer_config:
        optimizer: adam
        lr: 0.001
        l2: 0.0
        grad_clip: 1.0
        sgd_config:
            momentum: 0.9
        adam_config:
            betas: [0.9, 0.999]
            key: !!python/tuple [1, 2]
    lr_scheduler: